--[=[
HealersHaveToDie World of Warcraft Add-on
Copyright (c) 2009-2011 by John Wellesz (Archarodim@teaser.fr)
All rights reserved

Version 1.8.2_beta_1

This is a very simple and light add-on that rings when you hover or target a
unit of the opposite faction who healed someone during the last 60 seconds (can
be configured).
Now you can spot those nasty healers instantly and help them to accomplish their destiny!

This add-on uses the Ace3 framework.

type /hhtd to get a list of existing options.

-----
    Localization.lua
-----


--]=]


--[=[
--                      YOUR ATTENTION PLEASE
--
--         !!!!!!! TRANSLATORS TRANSLATORS TRANSLATORS !!!!!!!
--
--    Thank you very much for your interest in translating Healers Have To Die.
--    Do not edit this file. Use the localization interface available at the following address:
--
--      ##########################################################################
--      #  http://wow.curseforge.com/projects/healers-have-to-die/localization/  #
--      ##########################################################################
--
--    Your translations made using this interface will be automatically included in the next release.
--
--]=]


do
    local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "enUS", true, true);

    if L then
        L["ACTIVE"] = "Active!"
L["Announcer"] = "Announcer"
L["Announcer_DESC"] = "This module allows you to manage chat and sound alerts"
L["DESCRIPTION"] = "Spot those bloody healers instantly and help them accomplish their destiny! (PVP and PVE)"
L["DISABLED"] = [=[hhtd has been disabled!
Type '/hhtd on' to re-enable it.]=]
L["ENABLED"] = "enabled! Type /hhtd for a list of options"
L["HUMAN"] = "Human"
L["IDLE"] = "Idle"
L["IS_A_HEALER"] = "%s is a healer!"
L["NO_DATA"] = "No data"
L["NPC"] = "NPC"
L["NPH"] = "Name Plate Hooker"
L["NPH_DESC"] = "This module adds a red cross to enemy healers' name plates"
L["OPT_ANNOUNCE"] = "Show messages"
L["OPT_ANNOUNCE_DESC"] = "HHTD will display messages when you target or mouse-over an enemy healer."
L["OPT_CLEAR_LOGS"] = "Clear logs"
L["OPT_CORE_OPTIONS"] = "Core options"
L["OPT_DEBUG"] = "debug"
L["OPT_DEBUG_DESC"] = "Enables / disables debugging"
L["OPT_ENABLE_GEHR"] = "Enable Graphical Reporter"
L["OPT_ENABLE_GEHR_DESC"] = "Displays a graphical list of detected enemy healers with various features"
L["OPT_HEALER_FORGET_TIMER"] = "Healer Forget Timer"
L["OPT_HEALER_FORGET_TIMER_DESC"] = "Set the Healer Forget Timer (the time in seconds an enemy will remain considered has a healer)"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = "Heal amount (|cff00dd00%u|r) threshold"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "Healers won't be detected until they reach this cumulative amount of healing based on a percentage of your own maximum health. (has no effect in PVP when \\\"Healer specialization detection\\\" is checked)"
L["OPT_LOG"] = "Logging"
L["OPT_LOGS"] = "Logs"
L["OPT_LOGS_DESC"] = "Display HHTD detected healers and statistics"
L["OPT_LOG_DESC"] = "Enables logging and adds a new 'Logs' tab to HHTD's option panel"
L["OPT_MODULES"] = "Modules"
L["OPT_NPH_WARNING1"] = [=[WARNING: Enemies' name-plates are currently disabled. HHTD cannot add its red cross symbol.
You can enable name-plates display through the WoW UI's options or by using the assigned key-stroke.]=]
L["OPT_NPH_WARNING2"] = [=[WARNING: Allies' name-plates are currently disabled. HHTD cannot add its healer symbol.
You can enable name-plates display through the WoW UI's options or by using the assigned key-stroke.]=]
L["OPT_OFF"] = "off"
L["OPT_OFF_DESC"] = "Disables HHTD"
L["OPT_ON"] = "on"
L["OPT_ON_DESC"] = "Enables HHTD"
L["OPT_PVE"] = "Enable for PVE"
L["OPT_PVE_DESC"] = "HHTD will also work for NPCs."
L["OPT_PVPHEALERSSPECSONLY"] = "Healer specialization detection"
L["OPT_PVPHEALERSSPECSONLY_DESC"] = "Only detect players specialized in healing. (this disables minimum heal amount filter for PVP)"
L["OPT_SOUNDS"] = "Sound alerts"
L["OPT_SOUNDS_DESC"] = "HHTD will play a specific sound when you hover or target an enemy healer"
L["OPT_STRICTGUIDPVE"] = "Accurate PVE detection"
L["OPT_STRICTGUIDPVE_DESC"] = "When several NPCs share the same name, HHTD will only add a cross over those who actually healed instead of adding a cross to all of them. Note that most of the time, you'll need to target or mouse-over the unit for the cross to appear."
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = "Use minimum heal amount filter"
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "Healers will have to heal for a specified amount before being tagged as such."
L["OPT_VERSION"] = "version"
L["OPT_VERSION_DESC"] = "Display version and release date"
L["RELEASE_DATE"] = "Release Date:"
L["VERSION"] = "version:"
L["YOU_GOT_HER"] = "You got %sher|r!"
L["YOU_GOT_HIM"] = "You got %shim|r!"
L["YOU_GOT_IT"] = "You got %sit|r!"


    

    end

end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "frFR");

    if L then
        L["ACTIVE"] = "Actif !"
L["Announcer"] = "Annonceur"
L["Announcer_DESC"] = "Ce module permet de gérer différents type d'alertes."
L["DESCRIPTION"] = "Débusquez ces maudits soigneurs instantanément et aider-les à accomplir leur destinée ! (JCJ et JCE)"
L["DISABLED"] = [=[hhtd a été désactivé !
Taper '/hhtd on' pour le réactiver]=]
L["ENABLED"] = "activé ! Taper /hhtd pour voir la liste des options"
L["HUMAN"] = "Humain"
L["IDLE"] = "Dormant"
L["IS_A_HEALER"] = "%s est un soigneur !"
L["NO_DATA"] = "Aucune donnée"
L["NPC"] = "PNJ"
L["NPH"] = "Barres d'info"
L["NPH_DESC"] = "Ce module ajoute une croix rouge au dessus des barres d'info des soigneurs ennemis."
L["OPT_ANNOUNCE"] = "Afficher les messages."
L["OPT_ANNOUNCE_DESC"] = "HHTD affiche des messages lorsque vous ciblez ou survolez des soigneurs ennemis avec la souris."
L["OPT_CLEAR_LOGS"] = "Effacer les journaux"
L["OPT_CORE_OPTIONS"] = "Options Générales"
L["OPT_DEBUG"] = "débuggage"
L["OPT_DEBUG_DESC"] = "Active / désactive le débuggage"
L["OPT_ENABLE_GEHR"] = "Activer le rapporteur graphique"
L["OPT_ENABLE_GEHR_DESC"] = "Affiche une interface listant les soigneurs ennemis."
L["OPT_HEALER_FORGET_TIMER"] = "Délai d'oubli des soigneurs"
L["OPT_HEALER_FORGET_TIMER_DESC"] = "Règle le délai d'oubli des soigneurs (le temps en secondes où un ennemi sera considéré comme soigneur)"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = "Seuil de soins (|cff00dd00%u|r)"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "Les soigneurs ne seront détectés qu'à partir de ce seuil de soin basé sur un pourcentage de vos points de vie maximales. (n'a pas d'effet en PVP si l'option \"Détection des spécialisations en soin\" est cochée)."
L["OPT_LOG"] = "Journalisation"
L["OPT_LOGS"] = "Journaux"
L["OPT_LOGS_DESC"] = "Affiche les soigneurs détectés par HHTD et des statistiques."
L["OPT_LOG_DESC"] = "Active la journalisation et ajoute un onglet 'Journaux' aux panneau des options de HHTD"
L["OPT_MODULES"] = "Modules"
L["OPT_NPH_WARNING1"] = [=[ATTENTION : Les barres d'infos des unités ennemies sont désactivées. HHTD ne peut pas ajouter sa croix rouge.
Vous pouvez activer les barres d'infos dans les options d'interface de WoW ou en utilisant le raccourcis.]=]
L["OPT_NPH_WARNING2"] = [=[ATTENTION : Les barres d'infos des unités alliées sont désactivées. HHTD ne peut pas ajouter son symbole de soigneur.
Vous pouvez activer les barres d'infos dans les options d'interface de WoW ou en utilisant le raccourcis.]=]
L["OPT_OFF"] = "désactivé"
L["OPT_OFF_DESC"] = "Désactive HHTD"
L["OPT_ON"] = "activé"
L["OPT_ON_DESC"] = "Active HHTD"
L["OPT_PVE"] = "Activer en PVE"
L["OPT_PVE_DESC"] = "HHTD fonctionnera également avec les personnages non joueurs (PNJs)"
L["OPT_PVPHEALERSSPECSONLY"] = "Détection des spécialisations en soin"
L["OPT_PVPHEALERSSPECSONLY_DESC"] = "Ne détectera que les joueurs spécialisés en soins. (Cela désactive le filtrage sur les soins cumulés en PVP)"
L["OPT_SOUNDS"] = "Alertes sonores"
L["OPT_SOUNDS_DESC"] = "HHTD joue un son spécifique lorsque votre souris se trouve au dessus d'un soigneur ennemi ou lorsque vous en ciblez un."
L["OPT_STRICTGUIDPVE"] = "Détection PVE précise"
L["OPT_STRICTGUIDPVE_DESC"] = "Quand plusieurs PNJ partagent le même nom, HHTD n'ajoutera une croix qu'à ceux qui ont réellement soigné au lieu d'en ajouter une à tous. Notez qu'il vous faudra cibler ou survoler les unités avec la souris pour que les croix apparaissent."
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = "Filtrage sur soins cumulés"
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "Les soigneurs devront cumuler un certain minimum de soins avant d'être considérés comme tel."
L["OPT_VERSION"] = "version"
L["OPT_VERSION_DESC"] = "Affiche la version et la date de sortie"
L["RELEASE_DATE"] = "Date de sortie :"
L["VERSION"] = "Version :"
L["YOU_GOT_HER"] = "Vous %sla|r tenez !"
L["YOU_GOT_HIM"] = "Vous %sle|r tenez !"
L["YOU_GOT_IT"] = "Vous %sle|r tenez !"

    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "deDE");

    if L then
        -- L["ACTIVE"] = ""
L["Announcer"] = "Melder"
L["Announcer_DESC"] = "Dieses Modul erlaubt dir Chat-Warnungen und Alarmtöne einzustellen"
L["DESCRIPTION"] = "Entdecke auf der Stelle diese verdammten Heiler und sorge dafür daß sie Ihr Schicksal ereilt! (PVE und PVP)"
L["DISABLED"] = [=[hhtd wurde deaktiviert!
Gib /hhtd ein, um es wieder zu aktivieren.]=] -- Needs review
L["ENABLED"] = "aktiviert! Für eine Optionsliste gib /hhtd ein."
-- L["HUMAN"] = ""
-- L["IDLE"] = ""
L["IS_A_HEALER"] = "%s ist ein Heiler!"
-- L["NO_DATA"] = ""
-- L["NPC"] = ""
L["NPH"] = "Namensschildanker"
L["NPH_DESC"] = "Dieses Modul fügt den feindlichen Heilern ein rotes Kreuz auf den Namensschildern hinzu"
L["OPT_ANNOUNCE"] = "Mitteilungen anzeigen"
L["OPT_ANNOUNCE_DESC"] = "HHTD wird Mitteilungen anzeigen, wenn du auf einen feindlichen Heiler zielst oder die Maus über ihn bewegst."
-- L["OPT_CLEAR_LOGS"] = ""
L["OPT_CORE_OPTIONS"] = "Hauptoptionen"
L["OPT_DEBUG"] = "Fehler suchen"
L["OPT_DEBUG_DESC"] = "Fehlersuche aktivieren / deaktivieren"
L["OPT_ENABLE_GEHR"] = "Graphischen Bericht aktivieren"
L["OPT_ENABLE_GEHR_DESC"] = "Zeigt eine graphische Liste der entdeckten feindlichen Heiler mit verschiedenen Eigenschaften an."
L["OPT_HEALER_FORGET_TIMER"] = "\"Heiler-vergessen\" Timer"
L["OPT_HEALER_FORGET_TIMER_DESC"] = "Den \"Heiler-vergessen\" Timer einstellen (die Zeit in Sekunden, für deren Dauer ein Feind als Heiler betrachtet wird)"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = "Mindestmenge an gesamter Heilung (|cff00dd00%u|r)" -- Needs review
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "Heiler werden nicht erkannt bis sie die \"Mindestmenge an gesamter Heilung\" erreicht haben (hat keine Auswirkung in PVP, falls \\\"Heiler Spezialisierungserkennung\" aktiviert ist)." -- Needs review
-- L["OPT_LOG"] = ""
-- L["OPT_LOGS"] = ""
-- L["OPT_LOGS_DESC"] = ""
-- L["OPT_LOG_DESC"] = ""
L["OPT_MODULES"] = "Module"
-- L["OPT_NPH_WARNING1"] = ""
-- L["OPT_NPH_WARNING2"] = ""
L["OPT_OFF"] = "aus"
L["OPT_OFF_DESC"] = "Deaktiviert HHTD"
L["OPT_ON"] = "an"
L["OPT_ON_DESC"] = "Aktiviert HHTD"
L["OPT_PVE"] = "PVE-Option aktivieren"
L["OPT_PVE_DESC"] = "HHTD wird NPCs einbeziehen"
L["OPT_PVPHEALERSSPECSONLY"] = "Heiler Spezialisierungserkennung"
L["OPT_PVPHEALERSSPECSONLY_DESC"] = "Erkenne nur Spieler die in Heilung spezialisiert sind. (Dies deaktiviert den \"Minimale Menge an Heilung\" Filter für PVP.)"
L["OPT_SOUNDS"] = "Alarmtöne oder akustische Warnmeldungen" -- Needs review
L["OPT_SOUNDS_DESC"] = "HHTD wird einen bestimmten Sound abspielen, wenn du auf einen feindlichen Heiler zielst oder die Maus über ihn bewegst."
L["OPT_STRICTGUIDPVE"] = "Genaue PVE-Erkennung"
L["OPT_STRICTGUIDPVE_DESC"] = "Bei namensgleichen NPCs wird HHTD nur solchen NPCs ein rotes Kreuz hinzufügen, welche auch tatsächlich geheilt haben und nicht allen. Denke daran, daß Du meistens den NPC im Ziel haben oder mit der Maus darüber fahren mußt, damit das Kreuz erscheint."
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = "Benutze den \"Minimale Menge an Heilung\" Filter"
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "Heiler müssen für die genannte Menge heilen, bevor sie als solche markiert werden."
L["OPT_VERSION"] = "Version"
L["OPT_VERSION_DESC"] = "Version und Veröffentlichungsdatum anzeigen"
L["RELEASE_DATE"] = "Veröffentlichungsdatum: "
L["VERSION"] = "Version:"
L["YOU_GOT_HER"] = "Du hast %ssie|r!"
L["YOU_GOT_HIM"] = "Du hast %sihn|r!"
L["YOU_GOT_IT"] = "Du hast %ses|r!"

    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "esES");

    if L then
        -- L["ACTIVE"] = ""
L["Announcer"] = "Anunciador"
L["Announcer_DESC"] = "Este módulo te permite gestionar las alertas de chat y sonido."
-- L["DESCRIPTION"] = ""
L["DISABLED"] = [=[hhtd ha sido desactivado!
Escribe /hhtd enable para reactivarlo.]=] -- Needs review
L["ENABLED"] = "¡Activado! Escribe /hhtd para una lista de opciones."
-- L["HUMAN"] = ""
-- L["IDLE"] = ""
L["IS_A_HEALER"] = "¡%s es un sanador!"
-- L["NO_DATA"] = ""
-- L["NPC"] = ""
-- L["NPH"] = ""
L["NPH_DESC"] = "Este módulo añade una cruz roja a las placas de nombre de los sanadores enemigos."
L["OPT_ANNOUNCE"] = "Mostrar mensajes"
L["OPT_ANNOUNCE_DESC"] = "HHTD mostrará mensajes cuando selecciones o pases por encima el ratón de un sanador enemigo."
-- L["OPT_CLEAR_LOGS"] = ""
L["OPT_CORE_OPTIONS"] = "Opciones principales"
L["OPT_DEBUG"] = "Depurar"
L["OPT_DEBUG_DESC"] = "Activa / desactiva la depuración de errores"
L["OPT_ENABLE_GEHR"] = "Activa el Informe Gráfico"
L["OPT_ENABLE_GEHR_DESC"] = "Muestra una lista gráfica de sanadores enemigos detectados con diversas funciones"
L["OPT_HEALER_FORGET_TIMER"] = "Contador de olvido de sanador"
L["OPT_HEALER_FORGET_TIMER_DESC"] = "Establece el Contador de olvido de sanador (el tiempo en segundos en que un enemigo sigue siendo considerado como un sanador)"
-- L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = ""
-- L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = ""
-- L["OPT_LOG"] = ""
-- L["OPT_LOGS"] = ""
-- L["OPT_LOGS_DESC"] = ""
-- L["OPT_LOG_DESC"] = ""
L["OPT_MODULES"] = "Módulos"
-- L["OPT_NPH_WARNING1"] = ""
-- L["OPT_NPH_WARNING2"] = ""
-- L["OPT_OFF"] = ""
L["OPT_OFF_DESC"] = "Desactiva HHTD"
-- L["OPT_ON"] = ""
L["OPT_ON_DESC"] = "Activa HHTD"
L["OPT_PVE"] = "Activar para PVE"
L["OPT_PVE_DESC"] = "HHTD también trabajará con NPCs."
-- L["OPT_PVPHEALERSSPECSONLY"] = ""
-- L["OPT_PVPHEALERSSPECSONLY_DESC"] = ""
L["OPT_SOUNDS"] = "Sonidos de alerta"
L["OPT_SOUNDS_DESC"] = "HHTD activará un sonido específico cuando selecciones o pases el ratón por encima de un sanador enemigo"
L["OPT_STRICTGUIDPVE"] = "Detección refinada para PVE"
L["OPT_STRICTGUIDPVE_DESC"] = "Cuando varios NPCs compartan el mismo nombre, HHTD solo añadirá una cruz sobre aquellos que realmente curaron en vez de a todos. Toma nota de que la mayor parte del tiempo, necesitarás seleccionar o pasar el ratón por encima para que aparezca la cruz."
-- L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = ""
-- L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = ""
L["OPT_VERSION"] = "Versión"
L["OPT_VERSION_DESC"] = "Muestra la versión y la fecha de publicación"
L["RELEASE_DATE"] = "Fecha de publicación:"
L["VERSION"] = "Versión:"
-- L["YOU_GOT_HER"] = ""
-- L["YOU_GOT_HIM"] = ""
-- L["YOU_GOT_IT"] = ""

    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "esMX");

    if L then
        -- L["ACTIVE"] = ""
-- L["Announcer"] = ""
-- L["Announcer_DESC"] = ""
-- L["DESCRIPTION"] = ""
-- L["DISABLED"] = ""
-- L["ENABLED"] = ""
-- L["HUMAN"] = ""
-- L["IDLE"] = ""
-- L["IS_A_HEALER"] = ""
-- L["NO_DATA"] = ""
-- L["NPC"] = ""
-- L["NPH"] = ""
-- L["NPH_DESC"] = ""
-- L["OPT_ANNOUNCE"] = ""
-- L["OPT_ANNOUNCE_DESC"] = ""
-- L["OPT_CLEAR_LOGS"] = ""
-- L["OPT_CORE_OPTIONS"] = ""
-- L["OPT_DEBUG"] = ""
-- L["OPT_DEBUG_DESC"] = ""
-- L["OPT_ENABLE_GEHR"] = ""
-- L["OPT_ENABLE_GEHR_DESC"] = ""
-- L["OPT_HEALER_FORGET_TIMER"] = ""
-- L["OPT_HEALER_FORGET_TIMER_DESC"] = ""
-- L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = ""
-- L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = ""
-- L["OPT_LOG"] = ""
-- L["OPT_LOGS"] = ""
-- L["OPT_LOGS_DESC"] = ""
-- L["OPT_LOG_DESC"] = ""
-- L["OPT_MODULES"] = ""
-- L["OPT_NPH_WARNING1"] = ""
-- L["OPT_NPH_WARNING2"] = ""
-- L["OPT_OFF"] = ""
-- L["OPT_OFF_DESC"] = ""
-- L["OPT_ON"] = ""
-- L["OPT_ON_DESC"] = ""
-- L["OPT_PVE"] = ""
-- L["OPT_PVE_DESC"] = ""
-- L["OPT_PVPHEALERSSPECSONLY"] = ""
-- L["OPT_PVPHEALERSSPECSONLY_DESC"] = ""
-- L["OPT_SOUNDS"] = ""
-- L["OPT_SOUNDS_DESC"] = ""
-- L["OPT_STRICTGUIDPVE"] = ""
-- L["OPT_STRICTGUIDPVE_DESC"] = ""
-- L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = ""
-- L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = ""
-- L["OPT_VERSION"] = ""
-- L["OPT_VERSION_DESC"] = ""
-- L["RELEASE_DATE"] = ""
-- L["VERSION"] = ""
-- L["YOU_GOT_HER"] = ""
-- L["YOU_GOT_HIM"] = ""
-- L["YOU_GOT_IT"] = ""

    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "koKR");

    if L then
        -- L["ACTIVE"] = ""
-- L["Announcer"] = ""
-- L["Announcer_DESC"] = ""
-- L["DESCRIPTION"] = ""
-- L["DISABLED"] = ""
-- L["ENABLED"] = ""
-- L["HUMAN"] = ""
-- L["IDLE"] = ""
-- L["IS_A_HEALER"] = ""
-- L["NO_DATA"] = ""
-- L["NPC"] = ""
-- L["NPH"] = ""
-- L["NPH_DESC"] = ""
-- L["OPT_ANNOUNCE"] = ""
-- L["OPT_ANNOUNCE_DESC"] = ""
-- L["OPT_CLEAR_LOGS"] = ""
-- L["OPT_CORE_OPTIONS"] = ""
-- L["OPT_DEBUG"] = ""
-- L["OPT_DEBUG_DESC"] = ""
-- L["OPT_ENABLE_GEHR"] = ""
-- L["OPT_ENABLE_GEHR_DESC"] = ""
-- L["OPT_HEALER_FORGET_TIMER"] = ""
-- L["OPT_HEALER_FORGET_TIMER_DESC"] = ""
-- L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = ""
-- L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = ""
-- L["OPT_LOG"] = ""
-- L["OPT_LOGS"] = ""
-- L["OPT_LOGS_DESC"] = ""
-- L["OPT_LOG_DESC"] = ""
-- L["OPT_MODULES"] = ""
-- L["OPT_NPH_WARNING1"] = ""
-- L["OPT_NPH_WARNING2"] = ""
-- L["OPT_OFF"] = ""
-- L["OPT_OFF_DESC"] = ""
-- L["OPT_ON"] = ""
-- L["OPT_ON_DESC"] = ""
-- L["OPT_PVE"] = ""
-- L["OPT_PVE_DESC"] = ""
-- L["OPT_PVPHEALERSSPECSONLY"] = ""
-- L["OPT_PVPHEALERSSPECSONLY_DESC"] = ""
-- L["OPT_SOUNDS"] = ""
-- L["OPT_SOUNDS_DESC"] = ""
-- L["OPT_STRICTGUIDPVE"] = ""
-- L["OPT_STRICTGUIDPVE_DESC"] = ""
-- L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = ""
-- L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = ""
-- L["OPT_VERSION"] = ""
-- L["OPT_VERSION_DESC"] = ""
-- L["RELEASE_DATE"] = ""
-- L["VERSION"] = ""
-- L["YOU_GOT_HER"] = ""
-- L["YOU_GOT_HIM"] = ""
-- L["YOU_GOT_IT"] = ""

    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "zhCN");

    if L then
        -- L["ACTIVE"] = ""
L["Announcer"] = "通报" -- Needs review
L["Announcer_DESC"] = "这个模块运行你管理聊天和音效警报" -- Needs review
-- L["DESCRIPTION"] = ""
L["DISABLED"] = [=[hhtd 已经被停用了!
输入 /hhtd 来重新启用它。]=] -- Needs review
L["ENABLED"] = "已启用! 输入 /hhtd 开启选单"
-- L["HUMAN"] = ""
-- L["IDLE"] = ""
L["IS_A_HEALER"] = "%s 是治疗者!"
-- L["NO_DATA"] = ""
-- L["NPC"] = ""
-- L["NPH"] = ""
L["NPH_DESC"] = "这个模块在敌对治疗姓名板上方显示一个红十字" -- Needs review
L["OPT_ANNOUNCE"] = "显示讯息"
L["OPT_ANNOUNCE_DESC"] = "HHTD 当你的目标或是鼠标经过一个敌对治疗者时将显示讯息。"
-- L["OPT_CLEAR_LOGS"] = ""
L["OPT_CORE_OPTIONS"] = "核心配置选项"
L["OPT_DEBUG"] = "侦错"
L["OPT_DEBUG_DESC"] = "启用/禁用除错" -- Needs review
L["OPT_ENABLE_GEHR"] = "启用图形报告"
-- L["OPT_ENABLE_GEHR_DESC"] = ""
-- L["OPT_HEALER_FORGET_TIMER"] = ""
-- L["OPT_HEALER_FORGET_TIMER_DESC"] = ""
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = "治疗数量  (|cff00dd00%u|r) 阀值" -- Needs review
-- L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = ""
-- L["OPT_LOG"] = ""
-- L["OPT_LOGS"] = ""
-- L["OPT_LOGS_DESC"] = ""
-- L["OPT_LOG_DESC"] = ""
L["OPT_MODULES"] = "模块"
-- L["OPT_NPH_WARNING1"] = ""
-- L["OPT_NPH_WARNING2"] = ""
L["OPT_OFF"] = "关" -- Needs review
L["OPT_OFF_DESC"] = "停用 HHTD"
L["OPT_ON"] = "开" -- Needs review
L["OPT_ON_DESC"] = "启用 HHTD"
L["OPT_PVE"] = "PvE 启用" -- Needs review
L["OPT_PVE_DESC"] = "HHTD 同样作用于NPC." -- Needs review
L["OPT_PVPHEALERSSPECSONLY"] = "治疗特殊化检测" -- Needs review
-- L["OPT_PVPHEALERSSPECSONLY_DESC"] = ""
L["OPT_SOUNDS"] = "音效警报" -- Needs review
L["OPT_SOUNDS_DESC"] = "HHTD在当你鼠标悬停或目标到一个敌对治疗时播放特效的音效" -- Needs review
L["OPT_STRICTGUIDPVE"] = "精确 PvE 检测" -- Needs review
-- L["OPT_STRICTGUIDPVE_DESC"] = ""
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = "使用最少治疗数量过滤" -- Needs review
-- L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = ""
L["OPT_VERSION"] = "版本"
L["OPT_VERSION_DESC"] = "显示版本&测试数据"
L["RELEASE_DATE"] = "测试资料:"
L["VERSION"] = "版本:"
-- L["YOU_GOT_HER"] = ""
-- L["YOU_GOT_HIM"] = ""
-- L["YOU_GOT_IT"] = ""

    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "zhTW");

    if L then
        -- L["ACTIVE"] = ""
L["Announcer"] = "Announcer" -- Needs review
-- L["Announcer_DESC"] = ""
-- L["DESCRIPTION"] = ""
L["DISABLED"] = [=[hhtd 已經被停用了!
輸入 /hhtd 來重新啟用它。]=] -- Needs review
L["ENABLED"] = "已啟用! 輸入 /hhtd 開啟選單"
-- L["HUMAN"] = ""
-- L["IDLE"] = ""
L["IS_A_HEALER"] = "%s 是治療者!"
-- L["NO_DATA"] = ""
-- L["NPC"] = ""
-- L["NPH"] = ""
-- L["NPH_DESC"] = ""
L["OPT_ANNOUNCE"] = "顯示訊息"
L["OPT_ANNOUNCE_DESC"] = "HHTD 當你的目標或是滑鼠經過一個敵對治療者時將顯示訊息。"
-- L["OPT_CLEAR_LOGS"] = ""
L["OPT_CORE_OPTIONS"] = "核心配置選項"
L["OPT_DEBUG"] = "偵錯"
L["OPT_DEBUG_DESC"] = "啟用/停用 偵錯" -- Needs review
L["OPT_ENABLE_GEHR"] = "啟用圖形報告"
L["OPT_ENABLE_GEHR_DESC"] = "Displays a graphical list of detected enemy healers with various features" -- Needs review
L["OPT_HEALER_FORGET_TIMER"] = "治療者目標計時器" -- Needs review
L["OPT_HEALER_FORGET_TIMER_DESC"] = "Set the Healer Forget Timer (the time in seconds an enemy will remain considered has a healer)" -- Needs review
-- L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = ""
-- L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = ""
-- L["OPT_LOG"] = ""
-- L["OPT_LOGS"] = ""
-- L["OPT_LOGS_DESC"] = ""
-- L["OPT_LOG_DESC"] = ""
L["OPT_MODULES"] = "模組"
-- L["OPT_NPH_WARNING1"] = ""
-- L["OPT_NPH_WARNING2"] = ""
L["OPT_OFF"] = "關" -- Needs review
L["OPT_OFF_DESC"] = "停用 HHTD"
L["OPT_ON"] = "開" -- Needs review
L["OPT_ON_DESC"] = "啟用 HHTD"
-- L["OPT_PVE"] = ""
-- L["OPT_PVE_DESC"] = ""
-- L["OPT_PVPHEALERSSPECSONLY"] = ""
-- L["OPT_PVPHEALERSSPECSONLY_DESC"] = ""
L["OPT_SOUNDS"] = "警報音效"
-- L["OPT_SOUNDS_DESC"] = ""
-- L["OPT_STRICTGUIDPVE"] = ""
-- L["OPT_STRICTGUIDPVE_DESC"] = ""
-- L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = ""
-- L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = ""
L["OPT_VERSION"] = "版本"
L["OPT_VERSION_DESC"] = "顯示版本&測試資料"
L["RELEASE_DATE"] = "測試資料:"
L["VERSION"] = "版本:"
L["YOU_GOT_HER"] = "You got %sher|r!" -- Needs review
L["YOU_GOT_HIM"] = "You got %shim|r!" -- Needs review
L["YOU_GOT_IT"] = "You got %sit|r!" -- Needs review

    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "ruRU");

    if L then
        -- L["ACTIVE"] = ""
L["Announcer"] = "Информатор"
L["Announcer_DESC"] = "Модуль настройки оповещений в чате и звуковых оповещений"
L["DESCRIPTION"] = "Мгновенный розыск кровавых лекарей и помощь предрешении их судьбы! (PVP и PVE)." -- Needs review
L["DISABLED"] = [=[HHTD выключен.
Введите /hhtd для включения.]=] -- Needs review
L["ENABLED"] = [=[HHTD включен!
Для просмотра возможных параметров введите команду /hhtd]=]
-- L["HUMAN"] = ""
-- L["IDLE"] = ""
L["IS_A_HEALER"] = "%s - лекарь!"
-- L["NO_DATA"] = ""
-- L["NPC"] = ""
L["NPH"] = "Подключение к индикаторам"
L["NPH_DESC"] = "Модуль, добавляющий красный крест к индикаторам здоровья вражеских лекарей" -- Needs review
L["OPT_ANNOUNCE"] = "Вывод сообщений"
L["OPT_ANNOUNCE_DESC"] = "HHTD выводит сообщения при выборе вражеского лекаря в цель или наведении на него мышкой"
-- L["OPT_CLEAR_LOGS"] = ""
L["OPT_CORE_OPTIONS"] = "Основные настройки"
L["OPT_DEBUG"] = "отладка"
L["OPT_DEBUG_DESC"] = "Включает/выключает режим отладки." -- Needs review
L["OPT_ENABLE_GEHR"] = "Включение графического информатора"
L["OPT_ENABLE_GEHR_DESC"] = "Включает графический список вражеских лекарей с разными дополнительными возможностями." -- Needs review
L["OPT_HEALER_FORGET_TIMER"] = "Таймер забывания лекарей"
L["OPT_HEALER_FORGET_TIMER_DESC"] = "Сколько времени в секундах помнить об обнаруженном лекаре." -- Needs review
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = "Порог количества лечения - (|cff00dd00%u|r)." -- Needs review
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "Лекари не будут обнаружены, пока они не достигнут выбранной общей суммы исцеления. Не работает в ПВП при включенной опции Обнаружение специализации лекаря." -- Needs review
-- L["OPT_LOG"] = ""
-- L["OPT_LOGS"] = ""
-- L["OPT_LOGS_DESC"] = ""
-- L["OPT_LOG_DESC"] = ""
L["OPT_MODULES"] = "Модули"
L["OPT_NPH_WARNING1"] = [=[ВНИМАНИЕ: Индикаторы здоровья врагов выключены! HHTD не сможет добавлять символ красного креста!
Вы можете включить индикаторы здоровья через опции интерфейса WoW или используя горячую клавишу.]=]
L["OPT_NPH_WARNING2"] = [=[ВНИМАНИЕ: Индикаторы здоровья союзников выключены! HHTD не сможет добавлять символ лекаря!
Вы можете включить индикаторы здоровья через опции интерфейса WoW или используя горячую клавишу.]=]
L["OPT_OFF"] = "off"
L["OPT_OFF_DESC"] = "Отключение HHTD." -- Needs review
L["OPT_ON"] = "on"
L["OPT_ON_DESC"] = "Включает HHTD"
L["OPT_PVE"] = "Включить для ПВЕ"
L["OPT_PVE_DESC"] = "Разрешить использование HHTD против НИП"
L["OPT_PVPHEALERSSPECSONLY"] = "Обнаружение специализации лекаря"
L["OPT_PVPHEALERSSPECSONLY_DESC"] = "Выявлять только игроков специализирующихся на исцелении. Эта опция отключает фильтр минимальной эффективности лечения в PvP." -- Needs review
L["OPT_SOUNDS"] = "Звуковые оповещения"
L["OPT_SOUNDS_DESC"] = "HHTD воспроизводит определенный звук при выборе лекаря в цель или наведении на него мышки"
L["OPT_STRICTGUIDPVE"] = "Точность отслеживания в ПВЕ-режиме"
L["OPT_STRICTGUIDPVE_DESC"] = "Если несколько НИП имеют одинаковые имена, HHTD добавит красный крест только к тому, который лечил в последнее время, а не ко всем сразу. В большинстве случаев понадобится выбрать НИП целью или навести на него мышь для появления креста."
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = "Фильтр минимальной эффективности лечения." -- Needs review
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "Лекарь должен исцелить на увазанную сумму, тогда он будет помечен как лекарь."
L["OPT_VERSION"] = "version"
L["OPT_VERSION_DESC"] = "Информация о версии и дате релиза"
L["RELEASE_DATE"] = "Дата выхода:"
L["VERSION"] = "Версия:" -- Needs review
L["YOU_GOT_HER"] = "Ты сделал %sее|r!"
L["YOU_GOT_HIM"] = "Ты сделал %sего|r!"
L["YOU_GOT_IT"] = "Ты сделал %sэто|r!"

    end
end


